export const selectName = {
  preferred_location: [
    'New York City',
    'San Francisco',
    'Seattle',
    'Los Angeles ',
    'Vancouver',
    'Beijing.China',
    'Shanghai.China'
  ],
  update_status_name: [
    'Full-time',
    'Full-time (contractor)',
    'Part-time',
    'Part-time(Contractor)',
    'Intern',
    'Actively looking',
    'Just look around'
  ],
  salary_range_name: [
    '0 - 5000',
    '5000 - 10000',
    '10000 - 15000',
    '15000 - 20000',
    '20000 - 30000',
    '30000 - 40000'
  ],

  year_length_name: ['0 - 1 Year', '1 - 3 Year', '3 - 5 Year', '5 + Year'],

  gender_arr: ['Male', 'Female', 'Other'],

  visa_arr: ['No Visa required', 'Yes'],

  compensation_arr: [
    'Annual Bonus',
    'Stock Option',
    'Stock Unit',
    'Health&Wellness',
    'Life&Accident Insurance',
    'Perk',
    '401k contribution'
  ],

  education_arr: ['High School', 'Bachelor', 'Master', 'Ph.D.', 'Other'],

  major_arr: [
    'Anthropology',
    'Architecture',
    'Biochemistry',
    'Biological Basis of Behavior',
    'Biology',
    'Biophysics',
    'Chemistry',
    'Cinema and Media Studies',
    'Classical Studies',
    'Cognitive Science',
    'Communication',
    'Comparative Literature and Theory',
    'Criminology',
    'Earth Science',
    'East Asian Area Studies',
    'East Asian Languages and Civilizations',
    'Economics',
    'Engineering Major',
    'English',
    'Environmental Studies',
    'Fine Arts',
    'French and Francophone Studies',
    "Gender, Sexuality and Women's Studies",
    'German',
    'Health and Societies',
    'Hispanic Studies',
    'History',
    'History of Art',
    'Huntsman Program in International Studies and Business',
    'Individualized Major',
    'International Relations',
    'Italian Studies',
    'Jewish Studies',
    'Latin American and Latino Studies',
    'Linguistics',
    'Logic, Information and Computation'
  ],

  degree: [
    'bachelor',
    'master',
    'phd',
    'other'
  ],

  city_arr: [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
    'Montgomery',
    'Juneau',
    'Phoenix',
    'Little Rock',
    'Sacramento',
    'Denver',
    'Hartford',
    'Dover',
    'Tallahassee',
    'Atlanta',
    'Honolulu',
    'Boise',
    'Springfield',
    'Indianapolis',
    'Des Moines',
    'Topeka',
    'Frankfort',
    'Baton Rouge',
    'Augusta',
    'Annapolis',
    'Boston',
    'Lansing',
    'St. Paul',
    'Jackson',
    'Jefferson City',
    'Helena',
    'Lincoln',
    'Carson City',
    'Concord',
    'Trenton',
    'Santa Fe',
    'Albany',
    'Raleigh',
    'Bismarck',
    'Columbus',
    'Oklahoma City',
    'Salem',
    'Harrisburg',
    'Providence',
    'Columbia',
    'Pierre',
    'Nashville',
    'Austin',
    'Salt Lake City',
    'Montpelier',
    'Richmond',
    'Olympia',
    'Charleston',
    'Madison',
    'Cheyenne'
  ],
  skill_arr: [
    'C#',
    'ASP.NET',
    'JavaScript',
    'Java',
    'J2EE',
    'LAMP',
    'PHP',
    'WCF',
    'WPF',
    'Silverlight',
    'H',
    'TML',
    'DHTML',
    'CSS',
    'VB.NET',
    'ADO.NET',
    'SOASOAP',
    'WSDL',
    'UDDI',
    'UML',
    'ASP',
    'VB',
    'ActiveX',
    'PL/SQL',
    'SP’s',
    'Indexes',
    'MTS',
    'IIS',
    'MS Commerce 2K Server',
    'WSS',
    'Ease Case',
    'VSS',
    'Maven',
    'XML',
    'DTD',
    'XSL',
    'XML DOM',
    'MTS',
    'weblogic',
    'Active Directory',
    'firewalls',
    'proxy servers',
    'load balancers',
    'Visio',
    'Mks',
    'VSS ',
    'Toad',
    'SQL',
    'ErWin',
    'Silk',
    'ACT',
    'Firewall',
    'AccuRev',
    'FORTRAN',
    'C',
    'BizTalk',
    'SharePoint',
    'TFS',
    'Bugzilla',
    'Siebel',
    'and SAP',
    'Android',
    'iOS',
    'VR',
    'Android Studio',
    'SDK',
    'AVD',
    'adb',
    'Selenium WD',
    'Appium',
    'IntelliJ',
    'Eclipse IDE',
    'Git',
    'JIRA',
    'TestRail',
    'YouTrack',
    'Git',
    'TeamCity',
    'Reporting Tools:',
    'Crystal Report, SSRS',
    'Database',
    'MS SQL Server,',
    'T-SQL',
    'Oracle',
    'DDL',
    'DML',
    'SQL JOIN',
    'Stored Procedures',
    'Function',
    'View',
    'Triggers',
    'IDE & RDBMS',
    'Visual Studio',
    'MS SQL Server',
    'Web Application Server',
    'IIS',
    'Version Control',
    'Team Foundation Server',
    'Automation Testing Tools',
    'Selenium IDE',
    'Web Driver',
    'QTP',
    'Firebug',
    'Fire Path',
    'Jenkins',
    'Requirement Management Tools',
    'Quality Center',
    'TFS',
    'Defect Tracking Tools',
    'Quality Center',
    'ALM',
    'JIRA',
    'Adobe Photoshop',
    'Adobe Flash'
  ]
}
