export const selectName = {
  preferred_location: [
    'New York City',
    'San Francisco',
    'Seattle',
    'Los Angeles ',
    'Vancouver',
    'Beijing.China',
    'Shanghai.China'
  ],
  update_status_name: [
    'Full-time',
    'Full-time (contractor)',
    'Part-time',
    'Part-time(Contractor)',
    'Intern',
    'Actively looking',
    'Just look around'
  ],
  employment_type: [
    'Full-time',
    'Full-time (contractor)',
    'Part-time',
    'Part-time(Contractor)',
    'Intern'
  ],
  salary_range_name: [
    '0 - 5000',
    '5000 - 10000',
    '10000 - 15000',
    '15000 - 20000',
    '20000 - 30000',
    '30000 - 40000'
  ],

  year_length_name: ['0 - 1 Year', '1 - 3 Year', '3 - 5 Year', '5 + Year'],

  gender_arr: ['Male', 'Female', 'Other'],

  visa_arr: ['No Visa required', 'Yes'],

  compensation_arr: [
    'Annual Bonus',
    'Stock Option',
    'Stock Unit',
    'Health&Wellness',
    'Life&Accident Insurance',
    'Perk',
    '401k contribution'
  ],

  education_arr: ['High School', 'Bachelor', 'Master', 'Ph.D.', 'Other'],

  major_arr: [
    'Anthropology',
    'Architecture',
    'Biochemistry',
    'Biological Basis of Behavior',
    'Biology',
    'Biophysics',
    'Chemistry',
    'Cinema and Media Studies',
    'Classical Studies',
    'Cognitive Science',
    'Communication',
    'Comparative Literature and Theory',
    'Criminology',
    'Earth Science',
    'East Asian Area Studies',
    'East Asian Languages and Civilizations',
    'Economics',
    'Engineering Major',
    'English',
    'Environmental Studies',
    'Fine Arts',
    'French and Francophone Studies',
    "Gender, Sexuality and Women's Studies",
    'German',
    'Health and Societies',
    'Hispanic Studies',
    'History',
    'History of Art',
    'Huntsman Program in International Studies and Business',
    'Individualized Major',
    'International Relations',
    'Italian Studies',
    'Jewish Studies',
    'Latin American and Latino Studies',
    'Linguistics',
    'Logic, Information and Computation'
  ],

  degree_arr: [
    'Bachelor',
    'Master',
    'Phd',
    'Other'
  ],

  city_arr: [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
    'Montgomery',
    'Juneau',
    'Phoenix',
    'Little Rock',
    'Sacramento',
    'Denver',
    'Hartford',
    'Dover',
    'Tallahassee',
    'Atlanta',
    'Honolulu',
    'Boise',
    'Springfield',
    'Indianapolis',
    'Des Moines',
    'Topeka',
    'Frankfort',
    'Baton Rouge',
    'Augusta',
    'Annapolis',
    'Boston',
    'Lansing',
    'St. Paul',
    'Jackson',
    'Jefferson City',
    'Helena',
    'Lincoln',
    'Carson City',
    'Concord',
    'Trenton',
    'Santa Fe',
    'Albany',
    'Raleigh',
    'Bismarck',
    'Columbus',
    'Oklahoma City',
    'Salem',
    'Harrisburg',
    'Providence',
    'Columbia',
    'Pierre',
    'Nashville',
    'Austin',
    'Salt Lake City',
    'Montpelier',
    'Richmond',
    'Olympia',
    'Charleston',
    'Madison',
    'Cheyenne'
  ],
  skill_arr: [
    'C#',
    'ASP.NET',
    'JavaScript',
    'Java',
    'J2EE',
    'LAMP',
    'PHP',
    'WCF',
    'WPF',
    'Silverlight',
    'H',
    'TML',
    'DHTML',
    'CSS',
    'VB.NET',
    'ADO.NET',
    'SOASOAP',
    'WSDL',
    'UDDI',
    'UML',
    'ASP',
    'VB',
    'ActiveX',
    'PL/SQL',
    'SP’s',
    'Indexes',
    'MTS',
    'IIS',
    'MS Commerce 2K Server',
    'WSS',
    'Ease Case',
    'VSS',
    'Maven',
    'XML',
    'DTD',
    'XSL',
    'XML DOM',
    'MTS',
    'weblogic',
    'Active Directory',
    'firewalls',
    'proxy servers',
    'load balancers',
    'Visio',
    'Mks',
    'VSS ',
    'Toad',
    'SQL',
    'ErWin',
    'Silk',
    'ACT',
    'Firewall',
    'AccuRev',
    'FORTRAN',
    'C',
    'BizTalk',
    'SharePoint',
    'TFS',
    'Bugzilla',
    'Siebel',
    'and SAP',
    'Android',
    'iOS',
    'VR',
    'Android Studio',
    'SDK',
    'AVD',
    'adb',
    'Selenium WD',
    'Appium',
    'IntelliJ',
    'Eclipse IDE',
    'Git',
    'JIRA',
    'TestRail',
    'YouTrack',
    'Git',
    'TeamCity',
    'Reporting Tools:',
    'Crystal Report, SSRS',
    'Database',
    'MS SQL Server,',
    'T-SQL',
    'Oracle',
    'DDL',
    'DML',
    'SQL JOIN',
    'Stored Procedures',
    'Function',
    'View',
    'Triggers',
    'IDE & RDBMS',
    'Visual Studio',
    'MS SQL Server',
    'Web Application Server',
    'IIS',
    'Version Control',
    'Team Foundation Server',
    'Automation Testing Tools',
    'Selenium IDE',
    'Web Driver',
    'QTP',
    'Firebug',
    'Fire Path',
    'Jenkins',
    'Requirement Management Tools',
    'Quality Center',
    'TFS',
    'Defect Tracking Tools',
    'Quality Center',
    'ALM',
    'JIRA',
    'Adobe Photoshop',
    'Adobe Flash'
  ],

  country_arr: [
    'AFGHANISTAN',
    'ALBANIA',
    'ALGERIA',
    'ANDORRA',
    'ANGOLA',
    'ANTIGUA & BARBUDA',
    'ARGENTINA',
    'ARMENIA',
    'AUSTRALIA',
    'AUSTRIA',
    'AZERBAIJAN',
    'BAHAMAS, THE',
    'BAHRAIN',
    'BANGLADESH',
    'BARBADOS',
    'BELARUS',
    'BELGIUM',
    'BELIZE',
    'BENIN',
    'BHUTAN',
    'BOLIVIA',
    'BOSNIA & HERZEGOVINA',
    'BOTSWANA',
    'BRAZIL',
    'BRUNEI',
    'BULGARIA',
    'BURKINA FASO',
    'BURUNDI',
    'CABO VERDE',
    'CAMBODIA',
    'CAMEROON',
    'CANADA',
    'CENTRAL AFRICAN REPUBLIC',
    'CHAD',
    'CHILE',
    'CHINA',
    'COLOMBIA',
    'COMOROS',
    'CONGO, DEMOCRATIC REPUBLIC OF THE',
    'COSTA RICA',
    "CÔTE D'IVOIRE",
    'CROATIA',
    'CUBA',
    'CYPRUS',
    'CZECH REPUBLIC',
    'DENMARK',
    'DJIBOUTI',
    'DOMINICA',
    'DOMINICAN REPUBLIC',
    'ECUADOR',
    'EGYPT',
    'EL SALVADOR',
    'EQUATORIAL GUINEA',
    'ERITREA',
    'ESTONIA',
    'ETHIOPIA',
    'FEDERATED STATES OF MICRONESIA',
    'FIJI',
    'FINLAND',
    'FRANCE',
    'GABON',
    'GAMBIA, THE',
    'GEORGIA',
    'GERMANY',
    'GHANA',
    'GREECE',
    'GRENADA',
    'GUATEMALA',
    'GUINEA',
    'GUINEA-BISSAU',
    'GUYANA',
    'HAITI',
    'HONDURAS',
    'HUNGARY',
    'ICELAND',
    'INDIA',
    'INDONESIA',
    'IRAN',
    'IRAQ',
    'IRELAND',
    'ISRAEL',
    'ITALY',
    'JAMAICA',
    'JAPAN',
    'JORDAN',
    'KAZAKHSTAN',
    'KENYA',
    'KIRIBATI',
    'KOSOVO',
    'KUWAIT',
    'KYRGYZSTAN',
    'LAOS',
    'LATVIA',
    'LEBANON',
    'LESOTHO',
    'LIBERIA',
    'LIBYA',
    'LIECHTENSTEIN',
    'LITHUANIA',
    'LUXEMBOURG',
    'MACEDONIA',
    'MADAGASCAR',
    'MALAWI',
    'MALAYSIA',
    'MALDIVES',
    'MALI',
    'MALTA',
    'MARSHALL ISLANDS',
    'MAURITANIA',
    'MAURITIUS',
    'MEXICO',
    'MOLDOVA',
    'MONACO',
    'MONGOLIA',
    'MONTENEGRO',
    'MOROCCO',
    'MOZAMBIQUE',
    'MYANMAR',
    'NAMIBIA',
    'NAURU',
    'NEPAL',
    'NETHERLANDS',
    'NEW ZEALAND',
    'NICARAGUA',
    'NIGER',
    'NIGERIA',
    'NORTH KOREA',
    'NORWAY',
    'OMAN',
    'PAKISTAN',
    'PALAU',
    'PALESTINE',
    'PANAMA',
    'PAPUA NEW GUINEA',
    'PARAGUAY',
    'PERU',
    'PHILIPPINES',
    'POLAND',
    'PORTUGAL',
    'QATAR',
    'REPUBLIC OF THE CONGO',
    'ROMANIA',
    'RUSSIA',
    'RWANDA',
    'SAINT KITTS & NEVIS',
    'SAINT LUCIA',
    'SAINT VINCENT & THE GRENADINES',
    'SAMOA',
    'SAN MARINO',
    'SÃO TOMÉ & PRÍNCIPE',
    'SAUDI ARABIA',
    'SENEGAL',
    'SERBIA',
    'SEYCHELLES',
    'SIERRA LEONE',
    'SINGAPORE',
    'SLOVAKIA',
    'SLOVENIA',
    'SOLOMON ISLANDS',
    'SOMALIA',
    'SOUTH AFRICA',
    'SOUTH KOREA',
    'SOUTH SUDAN',
    'SPAIN',
    'SRI LANKA',
    'SUDAN',
    'SURINAME',
    'SWAZILAND',
    'SWEDEN',
    'SWITZERLAND',
    'SYRIA',
    'TAJIKISTAN',
    'TANZANIA',
    'THAILAND',
    'TIMOR-LESTE',
    'TOGO',
    'TONGA',
    'TRINIDAD & TOBAGO',
    'TUNISIA',
    'TURKEY',
    'TURKMENISTAN',
    'TUVALU',
    'UGANDA',
    'UKRAINE',
    'UNITED ARAB EMIRATES',
    'UNITED KINGDOM',
    'UNITED STATES',
    'URUGUAY',
    'UZBEKISTAN',
    'VANUATU',
    'VATICAN CITY',
    'VENEZUELA',
    'VIETNAM',
    'YEMEN',
    'ZAMBIA',
    'ZIMBABWE'
  ],

  language_arr: [
    'Afrikaans',
    'Akan',
    'Albanian',
    'Amharic',
    'Arabic',
    'Armenian',
    'ASL',
    'Assamese',
    'Assyrian',
    'Azerbaijani',
    'Bahdini',
    'Bambara',
    'Bashkir',
    'Basque',
    'Belarusian',
    'Bengali',
    'Bosnian',
    'Bravanese',
    'Bulgarian',
    'Burmese',
    'Cambodian',
    'Cantonese',
    'Catalan',
    'Cebuano',
    'Chaldean',
    'Chamorro',
    'Chaozhou',
    'Chavacano',
    'Chin',
    'Chuukese',
    'Cree',
    'Croatian',
    'Czech',
    'Dakota',
    'Danish',
    'Dari',
    'Dinka',
    'Dioula',
    'Dutch',
    'Dzongkha',
    'English',
    'Estonian',
    'Ewe',
    'Fante',
    'Faroese',
    'Farsi',
    'Fijian Hindi',
    'Finnish',
    'Flemish',
    'French',
    'French Canadian',
    'Frisian',
    'Fujianese',
    'Fukienese',
    'Fula',
    'Fulani',
    'Fuzhou',
    'Ga',
    'Gaelic',
    'Galician',
    'Ganda',
    'Georgian',
    'German',
    'Gorani',
    'Greek',
    'Gujarati',
    'Haitian Creole',
    'Hakka',
    'Hassaniyya',
    'Hausa',
    'Hebrew',
    'Hiligaynon',
    'Hindi',
    'Hmong',
    'Hungarian',
    'Ibanag',
    'Icelandic',
    'Igbo',
    'Ilocano',
    'Ilonggo',
    'Indian',
    'Indonesian',
    'Inuktitut',
    'Irish',
    'Italian',
    'Jakartanese',
    'Japanese',
    'Javanese',
    'Kanjobal',
    'Kannada',
    'Karen',
    'Kashmiri',
    'Kazakh',
    'Khalkha',
    'Khmer',
    'Kikuyu',
    'Kinyarwanda',
    'Kirundi',
    'Korean',
    'Kosovan',
    'Kotokoli',
    'Krio',
    'Kurdish',
    'Kurmanji',
    'Kyrgyz',
    'Lakota',
    'Laotian',
    'Latin',
    'Latvian',
    'Lingala',
    'Lithuanian',
    'Luganda',
    'Luo',
    'Lusoga',
    'Luxembourgeois',
    'Maay',
    'Macedonian',
    'Malagasy',
    'Malay',
    'Malayalam',
    'Maldivian',
    'Maltese',
    'Mandarin',
    'Mandingo',
    'Mandinka',
    'Maori',
    'Marathi',
    'Marshallese',
    'Mien',
    'Mirpuri',
    'Mixteco',
    'Moldovan',
    'Mongolian',
    'Navajo',
    'Neapolitan',
    'Nepali',
    'Norwegian',
    'Nuer',
    'Nyanja',
    'Ojibaway',
    'Oriya',
    'Oromo',
    'Ossetian',
    'Pahari',
    'Pampangan',
    'Pashto',
    'Patois',
    'Pidgin English',
    'Polish',
    'Portuguese',
    'Pothwari',
    'Pulaar',
    'Punjabi',
    'Putian',
    'Quanxi',
    'Quechua',
    'Romani',
    'Romanian',
    'Romansch',
    'Rundi',
    'Russian',
    'Samoan',
    'Sango',
    'Sanskrit',
    'Serbian',
    'Shanghainese',
    'Shona',
    'Sichuan',
    'Sicilian',
    'Sindhi',
    'Sinhala',
    'Sinhalese',
    'Siswati/Swazi',
    'Slovak',
    'Slovene',
    'Slovenian',
    'Somali',
    'Soninke',
    'Sorani',
    'Sotho',
    'Spanish',
    'Sundanese',
    'Susu',
    'Swahili',
    'Swedish',
    'Sylhetti',
    'Tagalog',
    'Taiwanese',
    'Tajik',
    'Tamil',
    'Telugu',
    'Thai',
    'Tibetan',
    'Tigrinya',
    'Tongan',
    'Tshiluba',
    'Tsonga',
    'Tswana',
    'Turkish',
    'Turkmen',
    'Uighur',
    'Ukrainian',
    'Urdu',
    'Uzbek',
    'Venda',
    'Vietnamese',
    'Visayan',
    'Welsh',
    'Wolof',
    'Xhosa',
    'Yao',
    'Yiddish',
    'Yoruba',
    'Yupik',
    'Zulu'
  ]
}